using Archskipelagill.ArchipelagoCompat;
using BepInEx.Configuration;
using MonoMod.Cil;
using MonoMod.Utils;
using System;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace Archskipelagill.GameDataAccess;

public class SaveFileRedirect : Module<SaveFileRedirect> {

    ////// Initializer/Fields/Properties //////

    public string RunSuffix => _cfgRunSuffix.Value;
    public float OnlyActiveDrops => _cfgOnlyActiveDrops.Value;
    public bool NoStartingInventory => _cfgNoStartingInventory.Value;
    public bool SendNotifs => _cfgSendNotifs.Value;
    public bool ReceiveNotifs => _cfgReceiveNotifs.Value;
    public bool MuteNotifs => _cfgMuteNotifs.Value;

    private readonly ConfigEntry<string> _cfgRunSuffix;
    private readonly ConfigEntry<float> _cfgOnlyActiveDrops;
    private readonly ConfigEntry<bool> _cfgNoStartingInventory;
    private readonly ConfigEntry<bool> _cfgSendNotifs;
    private readonly ConfigEntry<bool> _cfgReceiveNotifs;
    private readonly ConfigEntry<bool> _cfgMuteNotifs;

    public SaveFileRedirect() {
        _cfgRunSuffix = Plugin.Instance.MainConfig.Bind<string>(new ConfigDefinition("Save/Load", "Run Suffix"), "default", new ConfigDescription("A suffix added to the custom save file redirect used by the client plugin. Must be changed if you want to participate in multiple Archipelago runs including this game simultaneously."));
        _cfgSendNotifs = Plugin.Instance.MainConfig.Bind<bool>(new ConfigDefinition("Special Effects", "Location Notifications"), true, new ConfigDescription("If true, notifications will be displayed for sent location checks. These will be queued and only display once a run is active."));
        _cfgReceiveNotifs = Plugin.Instance.MainConfig.Bind<bool>(new ConfigDefinition("Special Effects", "Item Notifications"), true, new ConfigDescription("If true, notifications will be displayed for received items. These will be queued and only display once a run is active."));
        _cfgOnlyActiveDrops = Plugin.Instance.MainConfig.Bind<float>(new ConfigDefinition("Special Effects", "Item Notifications: Only Active Drops"), 0f, new ConfigDescription("If above 0, only items sent/received this amount of time after the client is connected will generate notifications. Adjusted for your network conditions, this can filter out large batches of notifications generated by async play. Does not affect starting inventory; use the Ignore Starting Inventory setting instead.", new AcceptableValueRange<float>(0f, 60f)));
        _cfgNoStartingInventory = Plugin.Instance.MainConfig.Bind<bool>(new ConfigDefinition("Special Effects", "Item Notifications: Ignore Starting Inventory"), true, new ConfigDescription("If true, starting inventory items will not generate notifications."));
        _cfgMuteNotifs = Plugin.Instance.MainConfig.Bind<bool>(new ConfigDefinition("Special Effects", "Item Notifications: Mute"), false, new ConfigDescription("If true, item notifications will not play sound."));

        IL.JSONsaver.save += IL_JSONsaver_save;
        IL.JSONsaver.load += IL_JSONsaver_load;
        On.MoneyBagScript.addMoneyToBag += On_MoneyBagScript_addMoneyToBag;
        On.JSONsaver.save += On_JSONsaver_save;
        var cslGO = new GameObject(); //main menu JSONSaver uses a tag for ident/finding, so this should be safe from intercepting MoneyBagScript et al.
        UnityEngine.Object.DontDestroyOnLoad(cslGO);
        cslGO.AddComponent<ArchipelagoSaver>();
    }


    ////// MonoMod Hooks /////
    #region MonoMod Hooks
    private void On_JSONsaver_save(On.JSONsaver.orig_save orig, JSONsaver self) {
        orig(self);
        if(self != ArchipelagoSaver.Instance) {
            ArchipelagoSaver.Instance.metaProg.Clear();
            ArchipelagoSaver.Instance.metaProg.AddRange(self.metaProg);
        }
    }

    private void On_MoneyBagScript_addMoneyToBag(On.MoneyBagScript.orig_addMoneyToBag orig, MoneyBagScript self) {
        var mpo = GameObject.FindGameObjectWithTag("MetaProg");
        if(mpo != null && mpo.TryGetComponent<JSONsaver>(out var saver)) {
            if(!saver.metaProg.TryGetValue("archi_manualMetaMoney", out var manualMoneyStr))
                manualMoneyStr = "0";
            saver.metaProg["archi_manualMetaMoney"] = (int.Parse(manualMoneyStr) + self.amount).ToString(); //save this just in case we need to implement rebuilding total from manual collection + filler item count at some point
        }
        orig(self);
    }

    private void IL_JSONsaver_load(ILContext il) {
        ILCursor c = new(il);
        c.GotoNext(MoveType.After, x => x.MatchLdstr("/save.json"));
        c.EmitDelegate<Func<string, string>>((origStr) => $"/archi-save-{_cfgRunSuffix.Value}.json");
        c.GotoNext(MoveType.After, x => x.MatchLdstr("/save.json"));
        c.EmitDelegate<Func<string, string>>((origStr) => $"/archi-save-{_cfgRunSuffix.Value}.json");
    }

    private void IL_JSONsaver_save(ILContext il) {
        ILCursor c = new(il);
        c.GotoNext(MoveType.After, x => x.MatchLdstr("/save.json"));
        c.EmitDelegate<Func<string, string>>((origStr) => $"/archi-save-{_cfgRunSuffix.Value}.json");
    }
    #endregion


    ////// Public API //////
    
    public void Wipe() {
        if(SceneManager.GetActiveScene().name != "menu") {
            Plugin.BepinLogger.LogError("SaveFileRedirect.Wipe must be called from main menu");
            return;
        }
        var saver = GameObject.FindGameObjectWithTag("MetaProg").GetComponent<JSONsaver>();
        saver.metaProg = [];
        var mb = GameObject.FindGameObjectWithTag("MoneyBag");
        if(mb != null)
            GameObject.Destroy(mb);

        var chara = GameObject.FindGameObjectWithTag("Player").GetComponent<CharaStats>();
        chara.XP = 0;
        chara.totalXP = 0;
        chara.XPtoDisplay = 0;
        chara.updateXPtoDisplay();

        ArchipelagoSaver.Instance.Wipe();

        GameObject.FindFirstObjectByType<gridResetter>().resetMetaProg(); //also saves save file
    }
}
