using System.Collections.Generic;

namespace Archskipelagill;

public static partial class SkillTree {
    public static List<SkillNode> skillTree = [
        new SkillNode(SkillNodeType.STAT, [1, 8], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 185, -1, -1),
        new SkillNode(SkillNodeType.STAT, [0, 2, 9], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 600, -1, -1),
        new SkillNode(SkillNodeType.STAT, [10, 1], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 92, -1, -1),
        new SkillNode(SkillNodeType.STAT, [12, 4], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 377, -1, -1),
        new SkillNode(SkillNodeType.STAT, [5, 3, 13], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 263, -1, -1),
        new SkillNode(SkillNodeType.STAT, [14, 4], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 299, -1, -1),
        new SkillNode(SkillNodeType.PERK, [7, 18], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 372, -1, 0),
        new SkillNode(SkillNodeType.STAT, [8, 19, 6], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 354, -1, -1),
        new SkillNode(SkillNodeType.STAT, [0, 7, 20], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 182, -1, -1),
        new SkillNode(SkillNodeType.STAT, [1], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 572, -1, -1),
        new SkillNode(SkillNodeType.STAT, [2, 21, 11], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 512, -1, -1),
        new SkillNode(SkillNodeType.STAT, [10, 12, 22], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 480, -1, -1),
        new SkillNode(SkillNodeType.STAT, [23, 3, 11], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 340, -1, -1),
        new SkillNode(SkillNodeType.STAT, [4], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 376, -1, -1),
        new SkillNode(SkillNodeType.STAT, [5, 24, 15], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 357, -1, -1),
        new SkillNode(SkillNodeType.STAT, [14, 25, 16], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 435, -1, -1),
        new SkillNode(SkillNodeType.PERK, [15, 26], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 6, -1, 1),
        new SkillNode(SkillNodeType.PERK, [28], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 17, -1, 2),
        new SkillNode(SkillNodeType.STAT, [30, 6], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 402, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [7], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 664, 0, -1),
        new SkillNode(SkillNodeType.STAT, [31, 8], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 235, -1, -1),
        new SkillNode(SkillNodeType.STAT, [10, 32], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 283, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [11], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 669, 1, -1),
        new SkillNode(SkillNodeType.STAT, [12, 33], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 147, -1, -1),
        new SkillNode(SkillNodeType.STAT, [34, 14], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 494, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [15], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 647, 2, -1),
        new SkillNode(SkillNodeType.STAT, [35, 16], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 595, -1, -1),
        new SkillNode(SkillNodeType.PERK, [37], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 211, -1, 3),
        new SkillNode(SkillNodeType.STAT, [44, 29, 17], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 237, -1, -1),
        new SkillNode(SkillNodeType.STAT, [30, 28], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 485, -1, -1),
        new SkillNode(SkillNodeType.STAT, [18, 29, 45], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 19, -1, -1),
        new SkillNode(SkillNodeType.STAT, [46, 32, 20], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 68, -1, -1),
        new SkillNode(SkillNodeType.STAT, [47, 21, 31], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 41, -1, -1),
        new SkillNode(SkillNodeType.STAT, [34, 23, 48], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 588, -1, -1),
        new SkillNode(SkillNodeType.STAT, [24, 33, 49], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 47, -1, -1),
        new SkillNode(SkillNodeType.STAT, [36, 26, 50], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 602, -1, -1),
        new SkillNode(SkillNodeType.STAT, [37, 35], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 130, -1, -1),
        new SkillNode(SkillNodeType.STAT, [36, 51, 27], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 251, -1, -1),
        new SkillNode(SkillNodeType.STAT, [45], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 567, -1, -1),
        new SkillNode(SkillNodeType.STAT, [46], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 139, -1, -1),
        new SkillNode(SkillNodeType.STAT, [47], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 131, -1, -1),
        new SkillNode(SkillNodeType.STAT, [48], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 479, -1, -1),
        new SkillNode(SkillNodeType.STAT, [49], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 403, -1, -1),
        new SkillNode(SkillNodeType.STAT, [50], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 500, -1, -1),
        new SkillNode(SkillNodeType.STAT, [55, 28, 52], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 524, -1, -1),
        new SkillNode(SkillNodeType.STAT, [30, 57, 38], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 22, -1, -1),
        new SkillNode(SkillNodeType.STAT, [59, 31, 39], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 481, -1, -1),
        new SkillNode(SkillNodeType.STAT, [61, 32, 40], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 38, -1, -1),
        new SkillNode(SkillNodeType.STAT, [63, 33, 41], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 545, -1, -1),
        new SkillNode(SkillNodeType.STAT, [65, 34, 42], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 204, -1, -1),
        new SkillNode(SkillNodeType.STAT, [35, 67, 43], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 77, -1, -1),
        new SkillNode(SkillNodeType.STAT, [37, 69, 53], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 274, -1, -1),
        new SkillNode(SkillNodeType.STAT, [44], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 85, -1, -1),
        new SkillNode(SkillNodeType.STAT, [51], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 488, -1, -1),
        new SkillNode(SkillNodeType.STAT, [55, 71], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 618, -1, -1),
        new SkillNode(SkillNodeType.STAT, [54, 44, 72], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 81, -1, -1),
        new SkillNode(SkillNodeType.STAT, [74], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 36, -1, -1),
        new SkillNode(SkillNodeType.STAT, [58, 45, 75], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 286, -1, -1),
        new SkillNode(SkillNodeType.STAT, [59, 57, 76], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 225, -1, -1),
        new SkillNode(SkillNodeType.STAT, [46, 77, 58], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 32, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [78], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 666, 3, -1),
        new SkillNode(SkillNodeType.STAT, [47, 79, 62], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 537, -1, -1),
        new SkillNode(SkillNodeType.STAT, [63, 61], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 70, -1, -1),
        new SkillNode(SkillNodeType.STAT, [80, 62, 48], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 559, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [81], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 626, 4, -1),
        new SkillNode(SkillNodeType.STAT, [66, 82, 49], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 358, -1, -1),
        new SkillNode(SkillNodeType.STAT, [65, 67, 83], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 40, -1, -1),
        new SkillNode(SkillNodeType.STAT, [66, 50, 84], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 611, -1, -1),
        new SkillNode(SkillNodeType.STAT, [85], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 4, -1, -1),
        new SkillNode(SkillNodeType.STAT, [70, 51, 87], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 539, -1, -1),
        new SkillNode(SkillNodeType.STAT, [88, 69], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 309, -1, -1),
        new SkillNode(SkillNodeType.STAT, [54, 89], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 386, -1, -1),
        new SkillNode(SkillNodeType.STAT, [73, 55, 90], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 535, -1, -1),
        new SkillNode(SkillNodeType.STAT, [74, 91, 72], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 64, -1, -1),
        new SkillNode(SkillNodeType.STAT, [73, 56, 75], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 254, -1, -1),
        new SkillNode(SkillNodeType.STAT, [74, 57, 92], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 392, -1, -1),
        new SkillNode(SkillNodeType.STAT, [58], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 215, -1, -1),
        new SkillNode(SkillNodeType.STAT, [93, 59, 78], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 511, -1, -1),
        new SkillNode(SkillNodeType.STAT, [79, 77, 60], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 195, -1, -1),
        new SkillNode(SkillNodeType.STAT, [94, 78, 61], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 592, -1, -1),
        new SkillNode(SkillNodeType.STAT, [63, 96, 81], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 229, -1, -1),
        new SkillNode(SkillNodeType.STAT, [82, 80, 64], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 14, -1, -1),
        new SkillNode(SkillNodeType.STAT, [65, 81, 97], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 118, -1, -1),
        new SkillNode(SkillNodeType.STAT, [66], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 216, -1, -1),
        new SkillNode(SkillNodeType.STAT, [85, 98, 67], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 163, -1, -1),
        new SkillNode(SkillNodeType.STAT, [86, 68, 84], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 262, -1, -1),
        new SkillNode(SkillNodeType.STAT, [85, 99, 87], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 387, -1, -1),
        new SkillNode(SkillNodeType.STAT, [100, 69, 86], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 74, -1, -1),
        new SkillNode(SkillNodeType.STAT, [70, 101], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 523, -1, -1),
        new SkillNode(SkillNodeType.STAT, [106, 71, 90], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 301, -1, -1),
        new SkillNode(SkillNodeType.PERK, [89, 107, 72], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 316, -1, 4),
        new SkillNode(SkillNodeType.CHEST, [73], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 635, 5, -1),
        new SkillNode(SkillNodeType.STAT, [108, 102, 75], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 16, -1, -1),
        new SkillNode(SkillNodeType.STAT, [77, 103, 109], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 58, -1, -1),
        new SkillNode(SkillNodeType.STAT, [110, 79, 95], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 50, -1, -1),
        new SkillNode(SkillNodeType.PERK, [94, 96], SkillNodeSpawnId.DWARVES, SkillNodeRegion.STRONGMAN, 151, -1, 5),
        new SkillNode(SkillNodeType.STAT, [111, 80, 95], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 71, -1, -1),
        new SkillNode(SkillNodeType.STAT, [82, 104, 112], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 179, -1, -1),
        new SkillNode(SkillNodeType.STAT, [113, 105, 84], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 259, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [86], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 670, 6, -1),
        new SkillNode(SkillNodeType.PERK, [101, 114, 87], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 190, -1, 6),
        new SkillNode(SkillNodeType.STAT, [115, 88, 100], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 319, -1, -1),
        new SkillNode(SkillNodeType.STAT, [92], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 62, -1, -1),
        new SkillNode(SkillNodeType.STAT, [93], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 476, -1, -1),
        new SkillNode(SkillNodeType.STAT, [97], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 457, -1, -1),
        new SkillNode(SkillNodeType.STAT, [98], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 307, -1, -1),
        new SkillNode(SkillNodeType.STAT, [89, 119], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 469, -1, -1),
        new SkillNode(SkillNodeType.STAT, [121, 90], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 25, -1, -1),
        new SkillNode(SkillNodeType.STAT, [92, 124, 109], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 236, -1, -1),
        new SkillNode(SkillNodeType.PERK, [108, 93, 125], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 560, -1, 7),
        new SkillNode(SkillNodeType.STAT, [127, 94, 116], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 531, -1, -1),
        new SkillNode(SkillNodeType.STAT, [128, 96, 117], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 582, -1, -1),
        new SkillNode(SkillNodeType.PERK, [113, 130, 97], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 413, -1, 8),
        new SkillNode(SkillNodeType.STAT, [131, 98, 112], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 201, -1, -1),
        new SkillNode(SkillNodeType.STAT, [134, 100], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 287, -1, -1),
        new SkillNode(SkillNodeType.STAT, [101, 136], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 404, -1, -1),
        new SkillNode(SkillNodeType.STAT, [110], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 109, -1, -1),
        new SkillNode(SkillNodeType.STAT, [111], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 239, -1, -1),
        new SkillNode(SkillNodeType.STAT, [138, 119], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 455, -1, -1),
        new SkillNode(SkillNodeType.STAT, [139, 106, 118], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 289, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [140], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 668, 7, -1),
        new SkillNode(SkillNodeType.STAT, [122, 141, 107], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 333, -1, -1),
        new SkillNode(SkillNodeType.STAT, [123, 121, 142], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 419, -1, -1),
        new SkillNode(SkillNodeType.STAT, [122, 124], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 448, -1, -1),
        new SkillNode(SkillNodeType.STAT, [143, 123, 108], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 37, -1, -1),
        new SkillNode(SkillNodeType.STAT, [144, 126, 109], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 594, -1, -1),
        new SkillNode(SkillNodeType.STAT, [127, 125, 145], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 145, -1, -1),
        new SkillNode(SkillNodeType.STAT, [126, 110, 146], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 209, -1, -1),
        new SkillNode(SkillNodeType.STAT, [111, 148, 129], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 580, -1, -1),
        new SkillNode(SkillNodeType.STAT, [130, 128, 149], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 265, -1, -1),
        new SkillNode(SkillNodeType.STAT, [129, 150, 112], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 407, -1, -1),
        new SkillNode(SkillNodeType.STAT, [151, 113, 132], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 0, -1, -1),
        new SkillNode(SkillNodeType.STAT, [131, 133], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 356, -1, -1),
        new SkillNode(SkillNodeType.STAT, [132, 134, 152], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 298, -1, -1),
        new SkillNode(SkillNodeType.STAT, [133, 114, 153], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 15, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [154], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 636, 8, -1),
        new SkillNode(SkillNodeType.STAT, [115, 155, 137], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 405, -1, -1),
        new SkillNode(SkillNodeType.STAT, [136, 156], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 302, -1, -1),
        new SkillNode(SkillNodeType.PERK, [159, 118], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 156, -1, 9),
        new SkillNode(SkillNodeType.STAT, [140, 119, 160], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 308, -1, -1),
        new SkillNode(SkillNodeType.STAT, [139, 141, 120], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 442, -1, -1),
        new SkillNode(SkillNodeType.STAT, [161, 121, 140], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 166, -1, -1),
        new SkillNode(SkillNodeType.STAT, [122], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 411, -1, -1),
        new SkillNode(SkillNodeType.STAT, [144, 162, 124], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 518, -1, -1),
        new SkillNode(SkillNodeType.STAT, [125, 143, 163], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 293, -1, -1),
        new SkillNode(SkillNodeType.STAT, [126], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 169, -1, -1),
        new SkillNode(SkillNodeType.STAT, [127, 164], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 508, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [165], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 652, 9, -1),
        new SkillNode(SkillNodeType.STAT, [128, 166], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 584, -1, -1),
        new SkillNode(SkillNodeType.STAT, [129], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 257, -1, -1),
        new SkillNode(SkillNodeType.STAT, [167, 130, 151], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 529, -1, -1),
        new SkillNode(SkillNodeType.STAT, [131, 168, 150], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 264, -1, -1),
        new SkillNode(SkillNodeType.STAT, [133], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 576, -1, -1),
        new SkillNode(SkillNodeType.STAT, [134, 169, 154], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 89, -1, -1),
        new SkillNode(SkillNodeType.STAT, [153, 155, 135], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 452, -1, -1),
        new SkillNode(SkillNodeType.STAT, [154, 136, 170], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 609, -1, -1),
        new SkillNode(SkillNodeType.PERK, [137, 171], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 381, -1, 10),
        new SkillNode(SkillNodeType.CHEST, [162], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 644, 10, -1),
        new SkillNode(SkillNodeType.CHEST, [168], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 628, 11, -1),
        new SkillNode(SkillNodeType.STAT, [138, 180], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 456, -1, -1),
        new SkillNode(SkillNodeType.STAT, [139, 181, 174], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 422, -1, -1),
        new SkillNode(SkillNodeType.STAT, [141, 182, 175], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 18, -1, -1),
        new SkillNode(SkillNodeType.STAT, [143, 184, 157], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 53, -1, -1),
        new SkillNode(SkillNodeType.STAT, [144, 185, 176], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 180, -1, -1),
        new SkillNode(SkillNodeType.STAT, [165, 146, 186], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 303, -1, -1),
        new SkillNode(SkillNodeType.STAT, [164, 166, 147], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 528, -1, -1),
        new SkillNode(SkillNodeType.STAT, [165, 148, 187], SkillNodeSpawnId.NONE, SkillNodeRegion.STRONGMAN, 107, -1, -1),
        new SkillNode(SkillNodeType.STAT, [150, 188, 177], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 441, -1, -1),
        new SkillNode(SkillNodeType.STAT, [189, 151, 158], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 513, -1, -1),
        new SkillNode(SkillNodeType.STAT, [191, 153, 178], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 375, -1, -1),
        new SkillNode(SkillNodeType.STAT, [155, 192, 179], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 487, -1, -1),
        new SkillNode(SkillNodeType.STAT, [156, 193], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 168, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [185], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 624, 12, -1),
        new SkillNode(SkillNodeType.CHEST, [188], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 637, 13, -1),
        new SkillNode(SkillNodeType.STAT, [160], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 75, -1, -1),
        new SkillNode(SkillNodeType.STAT, [161], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 136, -1, -1),
        new SkillNode(SkillNodeType.STAT, [163], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 117, -1, -1),
        new SkillNode(SkillNodeType.STAT, [167], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 484, -1, -1),
        new SkillNode(SkillNodeType.STAT, [169], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 496, -1, -1),
        new SkillNode(SkillNodeType.STAT, [170], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 329, -1, -1),
        new SkillNode(SkillNodeType.STAT, [181, 196, 159], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 207, -1, -1),
        new SkillNode(SkillNodeType.STAT, [180, 197, 160], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 562, -1, -1),
        new SkillNode(SkillNodeType.STAT, [183, 199, 161], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 116, -1, -1),
        new SkillNode(SkillNodeType.STAT, [184, 182], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 258, -1, -1),
        new SkillNode(SkillNodeType.STAT, [162, 200, 183], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 431, -1, -1),
        new SkillNode(SkillNodeType.STAT, [202, 163, 172], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 27, -1, -1),
        new SkillNode(SkillNodeType.STAT, [164, 203, 194], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 418, -1, -1),
        new SkillNode(SkillNodeType.STAT, [204, 166, 195], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 127, -1, -1),
        new SkillNode(SkillNodeType.STAT, [167, 205, 173], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 557, -1, -1),
        new SkillNode(SkillNodeType.STAT, [207, 168, 190], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 614, -1, -1),
        new SkillNode(SkillNodeType.STAT, [189, 191], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 397, -1, -1),
        new SkillNode(SkillNodeType.STAT, [190, 208, 169], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 296, -1, -1),
        new SkillNode(SkillNodeType.STAT, [193, 210, 170], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 324, -1, -1),
        new SkillNode(SkillNodeType.STAT, [192, 211, 171], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 55, -1, -1),
        new SkillNode(SkillNodeType.STAT, [186], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 621, -1, -1),
        new SkillNode(SkillNodeType.STAT, [187], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 363, -1, -1),
        new SkillNode(SkillNodeType.STAT, [219, 180], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 542, -1, -1),
        new SkillNode(SkillNodeType.STAT, [220, 181, 212], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 436, -1, -1),
        new SkillNode(SkillNodeType.STAT, [221], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 526, -1, -1),
        new SkillNode(SkillNodeType.STAT, [222, 182, 213], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 28, -1, -1),
        new SkillNode(SkillNodeType.STAT, [184, 223, 214], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 26, -1, -1),
        new SkillNode(SkillNodeType.STAT, [224], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 334, -1, -1),
        new SkillNode(SkillNodeType.STAT, [225, 203, 185], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 482, -1, -1),
        new SkillNode(SkillNodeType.STAT, [202, 186, 226], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 601, -1, -1),
        new SkillNode(SkillNodeType.STAT, [205, 187, 227], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 394, -1, -1),
        new SkillNode(SkillNodeType.STAT, [228, 204, 188], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 219, -1, -1),
        new SkillNode(SkillNodeType.STAT, [229], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 30, -1, -1),
        new SkillNode(SkillNodeType.STAT, [189, 230, 215], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 506, -1, -1),
        new SkillNode(SkillNodeType.STAT, [231, 191, 216], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 619, -1, -1),
        new SkillNode(SkillNodeType.STAT, [232], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 252, -1, -1),
        new SkillNode(SkillNodeType.STAT, [233, 192, 217], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 575, -1, -1),
        new SkillNode(SkillNodeType.STAT, [234, 193], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 556, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [197], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 646, 14, -1),
        new SkillNode(SkillNodeType.CHEST, [199], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 640, 15, -1),
        new SkillNode(SkillNodeType.STAT, [200], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 364, -1, -1),
        new SkillNode(SkillNodeType.STAT, [207], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 553, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [208], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 654, 16, -1),
        new SkillNode(SkillNodeType.CHEST, [210], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 642, 17, -1),
        new SkillNode(SkillNodeType.STAT, [236, 219], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 157, -1, -1),
        new SkillNode(SkillNodeType.STAT, [196, 218, 237], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 339, -1, -1),
        new SkillNode(SkillNodeType.STAT, [239, 197, 221], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 362, -1, -1),
        new SkillNode(SkillNodeType.STAT, [222, 198, 220], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 382, -1, -1),
        new SkillNode(SkillNodeType.STAT, [240, 221, 199], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 310, -1, -1),
        new SkillNode(SkillNodeType.STAT, [242, 224, 200], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 439, -1, -1),
        new SkillNode(SkillNodeType.STAT, [223, 225, 201], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 412, -1, -1),
        new SkillNode(SkillNodeType.STAT, [202, 224, 243], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 571, -1, -1),
        new SkillNode(SkillNodeType.STAT, [203, 244], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 84, -1, -1),
        new SkillNode(SkillNodeType.STAT, [204, 246], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 401, -1, -1),
        new SkillNode(SkillNodeType.STAT, [229, 205, 247], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 12, -1, -1),
        new SkillNode(SkillNodeType.STAT, [228, 230, 206], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 214, -1, -1),
        new SkillNode(SkillNodeType.STAT, [229, 207, 248], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 446, -1, -1),
        new SkillNode(SkillNodeType.STAT, [250, 232, 208], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 491, -1, -1),
        new SkillNode(SkillNodeType.STAT, [209, 231, 233], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 141, -1, -1),
        new SkillNode(SkillNodeType.STAT, [232, 210, 251], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 504, -1, -1),
        new SkillNode(SkillNodeType.STAT, [211, 235, 253], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 83, -1, -1),
        new SkillNode(SkillNodeType.STAT, [254, 234], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 241, -1, -1),
        new SkillNode(SkillNodeType.STAT, [259, 218], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 119, -1, -1),
        new SkillNode(SkillNodeType.PERK, [260, 219, 238], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 24, -1, 11),
        new SkillNode(SkillNodeType.STAT, [239, 237], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 517, -1, -1),
        new SkillNode(SkillNodeType.STAT, [261, 238, 220], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 603, -1, -1),
        new SkillNode(SkillNodeType.STAT, [222, 262], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 465, -1, -1),
        new SkillNode(SkillNodeType.STAT, [263], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 579, -1, -1),
        new SkillNode(SkillNodeType.PERK, [264, 223], SkillNodeSpawnId.FOX, SkillNodeRegion.DRAGON, 622, -1, 12),
        new SkillNode(SkillNodeType.STAT, [225, 265, 257], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 65, -1, -1),
        new SkillNode(SkillNodeType.STAT, [226, 245, 266], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 379, -1, -1),
        new SkillNode(SkillNodeType.PERK, [244, 246], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 477, -1, 13),
        new SkillNode(SkillNodeType.STAT, [245, 267, 227], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 351, -1, -1),
        new SkillNode(SkillNodeType.STAT, [228, 268, 258], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 52, -1, -1),
        new SkillNode(SkillNodeType.PERK, [269, 230], SkillNodeSpawnId.STRONGMAN, SkillNodeRegion.PROTOTYPE, 245, -1, 14),
        new SkillNode(SkillNodeType.STAT, [270], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 21, -1, -1),
        new SkillNode(SkillNodeType.STAT, [271, 231], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 408, -1, -1),
        new SkillNode(SkillNodeType.STAT, [272, 252, 233], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 530, -1, -1),
        new SkillNode(SkillNodeType.STAT, [251, 253], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 393, -1, -1),
        new SkillNode(SkillNodeType.PERK, [252, 234, 273], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 573, -1, 15),
        new SkillNode(SkillNodeType.STAT, [274, 235], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 318, -1, -1),
        new SkillNode(SkillNodeType.STAT, [261], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 406, -1, -1),
        new SkillNode(SkillNodeType.STAT, [272], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 297, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [243], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 662, 18, -1),
        new SkillNode(SkillNodeType.CHEST, [247], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 645, 19, -1),
        new SkillNode(SkillNodeType.STAT, [279, 236, 260], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 250, -1, -1),
        new SkillNode(SkillNodeType.STAT, [259, 280, 237], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 478, -1, -1),
        new SkillNode(SkillNodeType.STAT, [239, 281, 255], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 569, -1, -1),
        new SkillNode(SkillNodeType.STAT, [263, 240, 282], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 349, -1, -1),
        new SkillNode(SkillNodeType.STAT, [264, 262, 241], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 443, -1, -1),
        new SkillNode(SkillNodeType.STAT, [283, 242, 263], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 327, -1, -1),
        new SkillNode(SkillNodeType.STAT, [243, 266, 285], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 162, -1, -1),
        new SkillNode(SkillNodeType.STAT, [265, 244, 286], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 538, -1, -1),
        new SkillNode(SkillNodeType.STAT, [268, 246, 288], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 470, -1, -1),
        new SkillNode(SkillNodeType.STAT, [267, 247, 289], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 247, -1, -1),
        new SkillNode(SkillNodeType.STAT, [291, 270, 248], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 514, -1, -1),
        new SkillNode(SkillNodeType.STAT, [269, 271, 249], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 534, -1, -1),
        new SkillNode(SkillNodeType.STAT, [250, 292, 270], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 261, -1, -1),
        new SkillNode(SkillNodeType.STAT, [293, 251, 256], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 202, -1, -1),
        new SkillNode(SkillNodeType.STAT, [274, 294, 253], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 67, -1, -1),
        new SkillNode(SkillNodeType.STAT, [254, 295, 273], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 72, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [280], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 672, 20, -1),
        new SkillNode(SkillNodeType.CHEST, [282], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 659, 21, -1),
        new SkillNode(SkillNodeType.CHEST, [292], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 653, 22, -1),
        new SkillNode(SkillNodeType.CHEST, [294], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 632, 23, -1),
        new SkillNode(SkillNodeType.STAT, [301, 259, 296], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 444, -1, -1),
        new SkillNode(SkillNodeType.STAT, [302, 275, 260], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 233, -1, -1),
        new SkillNode(SkillNodeType.STAT, [261, 304], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 128, -1, -1),
        new SkillNode(SkillNodeType.STAT, [305, 262, 276], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 57, -1, -1),
        new SkillNode(SkillNodeType.STAT, [264, 307, 297], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 256, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [308], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 660, 24, -1),
        new SkillNode(SkillNodeType.STAT, [265, 309], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 326, -1, -1),
        new SkillNode(SkillNodeType.BOSS, [266, 310, 287, 334], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 181, -1, -1),
        new SkillNode(SkillNodeType.PERK, [286, 288], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 294, -1, 16),
        new SkillNode(SkillNodeType.BOSS, [267, 311, 287, 334], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 242, -1, -1),
        new SkillNode(SkillNodeType.STAT, [268, 312], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 290, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [313], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 661, 25, -1),
        new SkillNode(SkillNodeType.STAT, [314, 269, 298], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 95, -1, -1),
        new SkillNode(SkillNodeType.STAT, [271, 316, 277], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 350, -1, -1),
        new SkillNode(SkillNodeType.STAT, [272, 317], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 140, -1, -1),
        new SkillNode(SkillNodeType.STAT, [319, 278, 273], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 23, -1, -1),
        new SkillNode(SkillNodeType.STAT, [274, 320, 299], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 498, -1, -1),
        new SkillNode(SkillNodeType.STAT, [279], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 288, -1, -1),
        new SkillNode(SkillNodeType.STAT, [283], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 255, -1, -1),
        new SkillNode(SkillNodeType.STAT, [291], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 240, -1, -1),
        new SkillNode(SkillNodeType.STAT, [295], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 548, -1, -1),
        new SkillNode(SkillNodeType.PERK, [301], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 228, -1, 17),
        new SkillNode(SkillNodeType.STAT, [279, 324, 300], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 423, -1, -1),
        new SkillNode(SkillNodeType.STAT, [280, 322, 325], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 585, -1, -1),
        new SkillNode(SkillNodeType.STAT, [326], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 577, -1, -1),
        new SkillNode(SkillNodeType.STAT, [305, 327, 281], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 398, -1, -1),
        new SkillNode(SkillNodeType.STAT, [304, 282, 328], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 427, -1, -1),
        new SkillNode(SkillNodeType.STAT, [329], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 385, -1, -1),
        new SkillNode(SkillNodeType.STAT, [283, 331, 308], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 280, -1, -1),
        new SkillNode(SkillNodeType.STAT, [309, 307, 284], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 220, -1, -1),
        new SkillNode(SkillNodeType.STAT, [308, 332, 285], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 332, -1, -1),
        new SkillNode(SkillNodeType.PERK, [286, 333], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 544, -1, 18),
        new SkillNode(SkillNodeType.PERK, [288, 335], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 432, -1, 19),
        new SkillNode(SkillNodeType.STAT, [313, 336, 289], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 97, -1, -1),
        new SkillNode(SkillNodeType.STAT, [312, 314, 290], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 314, -1, -1),
        new SkillNode(SkillNodeType.STAT, [337, 291, 313], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 509, -1, -1),
        new SkillNode(SkillNodeType.STAT, [339], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 396, -1, -1),
        new SkillNode(SkillNodeType.STAT, [317, 292, 340], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 291, -1, -1),
        new SkillNode(SkillNodeType.STAT, [341, 293, 316], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 461, -1, -1),
        new SkillNode(SkillNodeType.STAT, [342], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 374, -1, -1),
        new SkillNode(SkillNodeType.STAT, [294, 323, 343], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 198, -1, -1),
        new SkillNode(SkillNodeType.STAT, [344, 295, 321], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 606, -1, -1),
        new SkillNode(SkillNodeType.PERK, [320], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 605, -1, 20),
        new SkillNode(SkillNodeType.STAT, [302], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 568, -1, -1),
        new SkillNode(SkillNodeType.STAT, [319], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 471, -1, -1),
        new SkillNode(SkillNodeType.STAT, [301, 345], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 192, -1, -1),
        new SkillNode(SkillNodeType.STAT, [326, 302, 347], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 210, -1, -1),
        new SkillNode(SkillNodeType.STAT, [327, 303, 325], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 203, -1, -1),
        new SkillNode(SkillNodeType.STAT, [326, 304, 348], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 20, -1, -1),
        new SkillNode(SkillNodeType.STAT, [305, 329, 349, 350], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 176, -1, -1),
        new SkillNode(SkillNodeType.STAT, [328, 330, 306], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 189, -1, -1),
        new SkillNode(SkillNodeType.STAT, [331, 329, 351], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 78, -1, -1),
        new SkillNode(SkillNodeType.STAT, [307, 352, 330], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 561, -1, -1),
        new SkillNode(SkillNodeType.STAT, [309, 354, 333], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 566, -1, -1),
        new SkillNode(SkillNodeType.BOSS, [332, 310, 355, 334], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 282, -1, -1),
        new SkillNode(SkillNodeType.BOSS_FINAL, [], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 177, -1, -1),
        new SkillNode(SkillNodeType.BOSS, [336, 311, 356, 334], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 13, -1, -1),
        new SkillNode(SkillNodeType.STAT, [312, 357, 335], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 112, -1, -1),
        new SkillNode(SkillNodeType.STAT, [338, 314, 359], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 7, -1, -1),
        new SkillNode(SkillNodeType.STAT, [337, 339, 360], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 221, -1, -1),
        new SkillNode(SkillNodeType.STAT, [338, 340, 315], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 268, -1, -1),
        new SkillNode(SkillNodeType.STAT, [316, 339, 361], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 281, -1, -1),
        new SkillNode(SkillNodeType.STAT, [342, 317, 362], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 232, -1, -1),
        new SkillNode(SkillNodeType.STAT, [341, 318, 343], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 466, -1, -1),
        new SkillNode(SkillNodeType.STAT, [342, 363, 319], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 132, -1, -1),
        new SkillNode(SkillNodeType.STAT, [365, 320], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 153, -1, -1),
        new SkillNode(SkillNodeType.STAT, [324, 370, 346], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 278, -1, -1),
        new SkillNode(SkillNodeType.STAT, [347, 345, 371], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 43, -1, -1),
        new SkillNode(SkillNodeType.STAT, [372, 346, 325], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 56, -1, -1),
        new SkillNode(SkillNodeType.PERK, [349, 350, 373, 327], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 322, -1, 21),
        new SkillNode(SkillNodeType.STAT, [374, 328, 350, 348], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 285, -1, -1),
        new SkillNode(SkillNodeType.STAT, [374, 328, 349, 348], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 589, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [330], SkillNodeSpawnId.NONE, SkillNodeRegion.DRAGON, 641, 26, -1),
        new SkillNode(SkillNodeType.STAT, [353, 331, 375], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 536, -1, -1),
        new SkillNode(SkillNodeType.STAT, [352, 354], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 331, -1, -1),
        new SkillNode(SkillNodeType.STAT, [353, 376, 332], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 196, -1, -1),
        new SkillNode(SkillNodeType.PERK, [333, 377], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 205, -1, 22),
        new SkillNode(SkillNodeType.PERK, [335, 379], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 102, -1, 23),
        new SkillNode(SkillNodeType.STAT, [358, 336, 380], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 194, -1, -1),
        new SkillNode(SkillNodeType.STAT, [359, 357], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 164, -1, -1),
        new SkillNode(SkillNodeType.STAT, [337, 358, 381], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 10, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [338], SkillNodeSpawnId.NONE, SkillNodeRegion.PROTOTYPE, 656, 27, -1),
        new SkillNode(SkillNodeType.STAT, [382, 340, 362], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 54, -1, -1),
        new SkillNode(SkillNodeType.PERK, [383, 361, 341], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 317, -1, 24),
        new SkillNode(SkillNodeType.STAT, [364, 384, 343], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 353, -1, -1),
        new SkillNode(SkillNodeType.STAT, [365, 363, 385], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 110, -1, -1),
        new SkillNode(SkillNodeType.STAT, [364, 386, 344], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 451, -1, -1),
        new SkillNode(SkillNodeType.STAT, [372], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 143, -1, -1),
        new SkillNode(SkillNodeType.STAT, [374], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 574, -1, -1),
        new SkillNode(SkillNodeType.STAT, [382], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 578, -1, -1),
        new SkillNode(SkillNodeType.STAT, [384], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 191, -1, -1),
        new SkillNode(SkillNodeType.STAT, [345, 391], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 360, -1, -1),
        new SkillNode(SkillNodeType.STAT, [346], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 134, -1, -1),
        new SkillNode(SkillNodeType.STAT, [347, 392, 366], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 170, -1, -1),
        new SkillNode(SkillNodeType.STAT, [393, 387, 348], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 243, -1, -1),
        new SkillNode(SkillNodeType.STAT, [394, 349, 350, 367], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 388, -1, -1),
        new SkillNode(SkillNodeType.STAT, [352, 396, 388], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 227, -1, -1),
        new SkillNode(SkillNodeType.PERK, [354, 397], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 501, -1, 25),
        new SkillNode(SkillNodeType.BOSS, [398, 378, 355, 334], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 173, -1, -1),
        new SkillNode(SkillNodeType.PERK, [377, 379], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 342, -1, 26),
        new SkillNode(SkillNodeType.BOSS, [399, 378, 356, 334], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 135, -1, -1),
        new SkillNode(SkillNodeType.PERK, [400, 357], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 63, -1, 27),
        new SkillNode(SkillNodeType.STAT, [401, 359, 389], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 597, -1, -1),
        new SkillNode(SkillNodeType.STAT, [361, 403, 368], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 8, -1, -1),
        new SkillNode(SkillNodeType.STAT, [404, 390, 362], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 328, -1, -1),
        new SkillNode(SkillNodeType.STAT, [405, 363, 369], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 472, -1, -1),
        new SkillNode(SkillNodeType.STAT, [364], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 430, -1, -1),
        new SkillNode(SkillNodeType.STAT, [365, 406], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 124, -1, -1),
        new SkillNode(SkillNodeType.STAT, [373], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 586, -1, -1),
        new SkillNode(SkillNodeType.STAT, [375], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 486, -1, -1),
        new SkillNode(SkillNodeType.STAT, [381], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 111, -1, -1),
        new SkillNode(SkillNodeType.STAT, [383], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 325, -1, -1),
        new SkillNode(SkillNodeType.PERK, [411, 370], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 593, -1, 28),
        new SkillNode(SkillNodeType.STAT, [372, 393, 412], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 370, -1, -1),
        new SkillNode(SkillNodeType.STAT, [413, 373, 392], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 99, -1, -1),
        new SkillNode(SkillNodeType.STAT, [395, 374, 414], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 270, -1, -1),
        new SkillNode(SkillNodeType.STAT, [396, 394], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 549, -1, -1),
        new SkillNode(SkillNodeType.STAT, [395, 375, 415], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 520, -1, -1),
        new SkillNode(SkillNodeType.STAT, [398, 417, 376], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 91, -1, -1),
        new SkillNode(SkillNodeType.STAT, [397, 418, 377], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 154, -1, -1),
        new SkillNode(SkillNodeType.STAT, [420, 400, 379], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 533, -1, -1),
        new SkillNode(SkillNodeType.STAT, [380, 421, 399], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 587, -1, -1),
        new SkillNode(SkillNodeType.STAT, [423, 381, 402], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 292, -1, -1),
        new SkillNode(SkillNodeType.STAT, [401, 403], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 515, -1, -1),
        new SkillNode(SkillNodeType.STAT, [424, 382, 402], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 366, -1, -1),
        new SkillNode(SkillNodeType.STAT, [425, 383, 405], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 361, -1, -1),
        new SkillNode(SkillNodeType.STAT, [404, 426, 384], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 468, -1, -1),
        new SkillNode(SkillNodeType.PERK, [386, 427], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 174, -1, 29),
        new SkillNode(SkillNodeType.CHEST, [411], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 650, 28, -1),
        new SkillNode(SkillNodeType.STAT, [412], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 335, -1, -1),
        new SkillNode(SkillNodeType.STAT, [426], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 246, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [427], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 639, 29, -1),
        new SkillNode(SkillNodeType.STAT, [434, 407, 391], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 100, -1, -1),
        new SkillNode(SkillNodeType.STAT, [436, 392, 408], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 253, -1, -1),
        new SkillNode(SkillNodeType.STAT, [437, 393, 428], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 93, -1, -1),
        new SkillNode(SkillNodeType.STAT, [438, 394, 429], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 244, -1, -1),
        new SkillNode(SkillNodeType.STAT, [396, 439, 430], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 368, -1, -1),
        new SkillNode(SkillNodeType.STAT, [440], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 105, -1, -1),
        new SkillNode(SkillNodeType.STAT, [441, 397], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 260, -1, -1),
        new SkillNode(SkillNodeType.STAT, [398, 419, 442], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 440, -1, -1),
        new SkillNode(SkillNodeType.STAT, [420, 418], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 273, -1, -1),
        new SkillNode(SkillNodeType.STAT, [399, 419, 443], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 495, -1, -1),
        new SkillNode(SkillNodeType.STAT, [444, 400], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 420, -1, -1),
        new SkillNode(SkillNodeType.STAT, [445], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 369, -1, -1),
        new SkillNode(SkillNodeType.STAT, [401, 446, 431], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 42, -1, -1),
        new SkillNode(SkillNodeType.STAT, [447, 403, 432], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 123, -1, -1),
        new SkillNode(SkillNodeType.STAT, [448, 404, 433], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 453, -1, -1),
        new SkillNode(SkillNodeType.STAT, [449, 405, 409], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 389, -1, -1),
        new SkillNode(SkillNodeType.STAT, [451, 410, 406], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 417, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [413], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 638, 30, -1),
        new SkillNode(SkillNodeType.STAT, [414], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 76, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [415], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 667, 31, -1),
        new SkillNode(SkillNodeType.CHEST, [423], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 643, 32, -1),
        new SkillNode(SkillNodeType.STAT, [424], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 599, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [425], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 655, 33, -1),
        new SkillNode(SkillNodeType.STAT, [454, 435, 411], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 149, -1, -1),
        new SkillNode(SkillNodeType.STAT, [434, 436], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 313, -1, -1),
        new SkillNode(SkillNodeType.STAT, [455, 435, 412], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 44, -1, -1),
        new SkillNode(SkillNodeType.STAT, [457, 413, 438], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 199, -1, -1),
        new SkillNode(SkillNodeType.STAT, [458, 437, 414], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 346, -1, -1),
        new SkillNode(SkillNodeType.STAT, [415, 440, 460], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 380, -1, -1),
        new SkillNode(SkillNodeType.STAT, [441, 439, 416], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 184, -1, -1),
        new SkillNode(SkillNodeType.STAT, [461, 417, 440], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 142, -1, -1),
        new SkillNode(SkillNodeType.STAT, [418, 462, 452], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 146, -1, -1),
        new SkillNode(SkillNodeType.STAT, [463, 420, 453], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 51, -1, -1),
        new SkillNode(SkillNodeType.STAT, [445, 421, 464], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 34, -1, -1),
        new SkillNode(SkillNodeType.STAT, [444, 446, 422], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 305, -1, -1),
        new SkillNode(SkillNodeType.STAT, [465, 445, 423], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 161, -1, -1),
        new SkillNode(SkillNodeType.STAT, [424, 448, 467], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 271, -1, -1),
        new SkillNode(SkillNodeType.STAT, [447, 425, 468], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 223, -1, -1),
        new SkillNode(SkillNodeType.STAT, [470, 450, 426], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 510, -1, -1),
        new SkillNode(SkillNodeType.STAT, [449, 451], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 519, -1, -1),
        new SkillNode(SkillNodeType.STAT, [471, 450, 427], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 29, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [442], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 663, 34, -1),
        new SkillNode(SkillNodeType.CHEST, [443], SkillNodeSpawnId.NONE, SkillNodeRegion.BOSS, 631, 35, -1),
        new SkillNode(SkillNodeType.STAT, [434, 476], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 103, -1, -1),
        new SkillNode(SkillNodeType.STAT, [436, 456, 477], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 464, -1, -1),
        new SkillNode(SkillNodeType.STAT, [455, 457, 478], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 391, -1, -1),
        new SkillNode(SkillNodeType.STAT, [437, 456, 479], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 96, -1, -1),
        new SkillNode(SkillNodeType.PERK, [480, 438], SkillNodeSpawnId.DRAGON, SkillNodeRegion.DWARVES, 234, -1, 30),
        new SkillNode(SkillNodeType.STAT, [481], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 607, -1, -1),
        new SkillNode(SkillNodeType.STAT, [482, 439], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 378, -1, -1),
        new SkillNode(SkillNodeType.STAT, [462, 441, 483], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 399, -1, -1),
        new SkillNode(SkillNodeType.STAT, [484, 461, 442], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 489, -1, -1),
        new SkillNode(SkillNodeType.STAT, [464, 485, 443], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 208, -1, -1),
        new SkillNode(SkillNodeType.STAT, [486, 444, 463], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 437, -1, -1),
        new SkillNode(SkillNodeType.STAT, [446, 487], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 213, -1, -1),
        new SkillNode(SkillNodeType.STAT, [488], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 540, -1, -1),
        new SkillNode(SkillNodeType.PERK, [489, 447], SkillNodeSpawnId.PROTOTYPE, SkillNodeRegion.FOX, 48, -1, 31),
        new SkillNode(SkillNodeType.STAT, [469, 448, 490], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 186, -1, -1),
        new SkillNode(SkillNodeType.STAT, [470, 468, 491], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 355, -1, -1),
        new SkillNode(SkillNodeType.STAT, [469, 492, 449], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 546, -1, -1),
        new SkillNode(SkillNodeType.STAT, [493, 451], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 414, -1, -1),
        new SkillNode(SkillNodeType.STAT, [476], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 499, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [483], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 649, 36, -1),
        new SkillNode(SkillNodeType.CHEST, [486], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 671, 37, -1),
        new SkillNode(SkillNodeType.STAT, [493], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 226, -1, -1),
        new SkillNode(SkillNodeType.STAT, [498, 454, 472], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 212, -1, -1),
        new SkillNode(SkillNodeType.STAT, [455, 499], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 610, -1, -1),
        new SkillNode(SkillNodeType.STAT, [456], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 267, -1, -1),
        new SkillNode(SkillNodeType.STAT, [500, 457], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 359, -1, -1),
        new SkillNode(SkillNodeType.STAT, [501, 458, 481], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 563, -1, -1),
        new SkillNode(SkillNodeType.STAT, [482, 480, 459], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 277, -1, -1),
        new SkillNode(SkillNodeType.STAT, [481, 502, 460], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 502, -1, -1),
        new SkillNode(SkillNodeType.STAT, [461, 503, 473], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 138, -1, -1),
        new SkillNode(SkillNodeType.STAT, [462, 504, 496], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 558, -1, -1),
        new SkillNode(SkillNodeType.STAT, [463, 506, 497], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 462, -1, -1),
        new SkillNode(SkillNodeType.STAT, [464, 507, 474], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 137, -1, -1),
        new SkillNode(SkillNodeType.STAT, [465, 488, 508], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 200, -1, -1),
        new SkillNode(SkillNodeType.STAT, [489, 487, 466], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 193, -1, -1),
        new SkillNode(SkillNodeType.STAT, [509, 488, 467], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 90, -1, -1),
        new SkillNode(SkillNodeType.STAT, [468, 510], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 425, -1, -1),
        new SkillNode(SkillNodeType.STAT, [469], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 31, -1, -1),
        new SkillNode(SkillNodeType.STAT, [470, 511], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 590, -1, -1),
        new SkillNode(SkillNodeType.STAT, [512, 471, 475], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 311, -1, -1),
        new SkillNode(SkillNodeType.STAT, [502], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 330, -1, -1),
        new SkillNode(SkillNodeType.STAT, [508], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 395, -1, -1),
        new SkillNode(SkillNodeType.STAT, [484], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 565, -1, -1),
        new SkillNode(SkillNodeType.STAT, [485], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 525, -1, -1),
        new SkillNode(SkillNodeType.STAT, [476, 499], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 86, -1, -1),
        new SkillNode(SkillNodeType.STAT, [519, 498, 477], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 284, -1, -1),
        new SkillNode(SkillNodeType.STAT, [501, 479, 520], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 238, -1, -1),
        new SkillNode(SkillNodeType.STAT, [500, 480, 521], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 222, -1, -1),
        new SkillNode(SkillNodeType.STAT, [482, 523, 494], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 269, -1, -1),
        new SkillNode(SkillNodeType.STAT, [524, 483, 517], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 458, -1, -1),
        new SkillNode(SkillNodeType.STAT, [525, 484, 505], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 503, -1, -1),
        new SkillNode(SkillNodeType.PERK, [504, 506], SkillNodeSpawnId.MAGE, SkillNodeRegion.MAGE, 248, -1, 32),
        new SkillNode(SkillNodeType.STAT, [526, 485, 505], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 338, -1, -1),
        new SkillNode(SkillNodeType.STAT, [486, 527, 518], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 66, -1, -1),
        new SkillNode(SkillNodeType.STAT, [528, 487, 495], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 167, -1, -1),
        new SkillNode(SkillNodeType.STAT, [530, 489, 510], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 206, -1, -1),
        new SkillNode(SkillNodeType.STAT, [509, 531, 490], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 551, -1, -1),
        new SkillNode(SkillNodeType.STAT, [532, 512, 492], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 447, -1, -1),
        new SkillNode(SkillNodeType.STAT, [493, 511], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 543, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [519], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 673, 38, -1),
        new SkillNode(SkillNodeType.STAT, [520], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 45, -1, -1),
        new SkillNode(SkillNodeType.STAT, [531], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 82, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [532], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 627, 39, -1),
        new SkillNode(SkillNodeType.STAT, [503], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 596, -1, -1),
        new SkillNode(SkillNodeType.STAT, [507], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 61, -1, -1),
        new SkillNode(SkillNodeType.STAT, [537, 499, 513], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 122, -1, -1),
        new SkillNode(SkillNodeType.STAT, [500, 539, 514], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 113, -1, -1),
        new SkillNode(SkillNodeType.STAT, [540, 501, 533], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 178, -1, -1),
        new SkillNode(SkillNodeType.STAT, [541], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 521, -1, -1),
        new SkillNode(SkillNodeType.STAT, [524, 502, 542], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 467, -1, -1),
        new SkillNode(SkillNodeType.STAT, [543, 503, 523], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 312, -1, -1),
        new SkillNode(SkillNodeType.STAT, [504, 545, 534], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 345, -1, -1),
        new SkillNode(SkillNodeType.STAT, [546, 506, 535], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 197, -1, -1),
        new SkillNode(SkillNodeType.STAT, [548, 507, 528], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 69, -1, -1),
        new SkillNode(SkillNodeType.STAT, [527, 508, 549], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 507, -1, -1),
        new SkillNode(SkillNodeType.STAT, [550], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 410, -1, -1),
        new SkillNode(SkillNodeType.STAT, [509, 551, 536], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 390, -1, -1),
        new SkillNode(SkillNodeType.STAT, [552, 510, 515], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 315, -1, -1),
        new SkillNode(SkillNodeType.STAT, [554, 511, 516], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 98, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [521], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 630, 40, -1),
        new SkillNode(SkillNodeType.STAT, [525], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 490, -1, -1),
        new SkillNode(SkillNodeType.STAT, [526], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 183, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [530], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 651, 41, -1),
        new SkillNode(SkillNodeType.STAT, [555, 538, 519], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 133, -1, -1),
        new SkillNode(SkillNodeType.STAT, [537, 539], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 428, -1, -1),
        new SkillNode(SkillNodeType.STAT, [538, 520, 556], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 434, -1, -1),
        new SkillNode(SkillNodeType.STAT, [558, 521, 541], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 101, -1, -1),
        new SkillNode(SkillNodeType.STAT, [540, 522, 542], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 165, -1, -1),
        new SkillNode(SkillNodeType.PERK, [541, 559, 523], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 106, -1, 33),
        new SkillNode(SkillNodeType.STAT, [544, 524, 560], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 463, -1, -1),
        new SkillNode(SkillNodeType.STAT, [543, 545, 561], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 347, -1, -1),
        new SkillNode(SkillNodeType.STAT, [544, 525, 562], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 11, -1, -1),
        new SkillNode(SkillNodeType.STAT, [526, 547, 564], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 608, -1, -1),
        new SkillNode(SkillNodeType.STAT, [546, 548, 565], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 492, -1, -1),
        new SkillNode(SkillNodeType.STAT, [547, 527, 566], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 564, -1, -1),
        new SkillNode(SkillNodeType.PERK, [550, 528, 567], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 554, -1, 34),
        new SkillNode(SkillNodeType.STAT, [551, 529, 549], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 88, -1, -1),
        new SkillNode(SkillNodeType.STAT, [550, 530, 568], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 344, -1, -1),
        new SkillNode(SkillNodeType.STAT, [531, 553, 570], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 373, -1, -1),
        new SkillNode(SkillNodeType.STAT, [552, 554], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 60, -1, -1),
        new SkillNode(SkillNodeType.STAT, [532, 571, 553], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 321, -1, -1),
        new SkillNode(SkillNodeType.STAT, [576, 537], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 217, -1, -1),
        new SkillNode(SkillNodeType.STAT, [539, 557, 577], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 617, -1, -1),
        new SkillNode(SkillNodeType.STAT, [558, 556, 578], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 152, -1, -1),
        new SkillNode(SkillNodeType.STAT, [540, 579, 557], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 126, -1, -1),
        new SkillNode(SkillNodeType.STAT, [560, 580, 542], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 527, -1, -1),
        new SkillNode(SkillNodeType.STAT, [543, 559, 581], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 159, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [544], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 625, 42, -1),
        new SkillNode(SkillNodeType.STAT, [582, 545], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 409, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [583], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 657, 43, -1),
        new SkillNode(SkillNodeType.STAT, [584, 546], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 5, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [547], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 633, 44, -1),
        new SkillNode(SkillNodeType.STAT, [548, 567, 585], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 348, -1, -1),
        new SkillNode(SkillNodeType.STAT, [586, 566, 549], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 79, -1, -1),
        new SkillNode(SkillNodeType.STAT, [551, 587, 569], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 620, -1, -1),
        new SkillNode(SkillNodeType.STAT, [568, 570, 588], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 249, -1, -1),
        new SkillNode(SkillNodeType.STAT, [552, 589, 569], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 125, -1, -1),
        new SkillNode(SkillNodeType.STAT, [590, 554], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 415, -1, -1),
        new SkillNode(SkillNodeType.STAT, [576], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 39, -1, -1),
        new SkillNode(SkillNodeType.STAT, [579], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 581, -1, -1),
        new SkillNode(SkillNodeType.STAT, [587], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 367, -1, -1),
        new SkillNode(SkillNodeType.STAT, [590], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 459, -1, -1),
        new SkillNode(SkillNodeType.STAT, [595, 555, 572], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 516, -1, -1),
        new SkillNode(SkillNodeType.STAT, [596, 556], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 224, -1, -1),
        new SkillNode(SkillNodeType.STAT, [557], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 104, -1, -1),
        new SkillNode(SkillNodeType.STAT, [558, 573, 597], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 108, -1, -1),
        new SkillNode(SkillNodeType.STAT, [559, 591, 598], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 73, -1, -1),
        new SkillNode(SkillNodeType.STAT, [599, 560], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 336, -1, -1),
        new SkillNode(SkillNodeType.STAT, [583, 562, 600], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 9, -1, -1),
        new SkillNode(SkillNodeType.STAT, [582, 584, 563], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 421, -1, -1),
        new SkillNode(SkillNodeType.STAT, [564, 583, 601], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 449, -1, -1),
        new SkillNode(SkillNodeType.STAT, [602, 566], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 550, -1, -1),
        new SkillNode(SkillNodeType.STAT, [567, 594, 603], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 555, -1, -1),
        new SkillNode(SkillNodeType.STAT, [568, 604, 574], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 371, -1, -1),
        new SkillNode(SkillNodeType.STAT, [569], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 172, -1, -1),
        new SkillNode(SkillNodeType.STAT, [605, 570], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 218, -1, -1),
        new SkillNode(SkillNodeType.STAT, [606, 571, 575], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 615, -1, -1),
        new SkillNode(SkillNodeType.STAT, [580], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 148, -1, -1),
        new SkillNode(SkillNodeType.STAT, [599], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 144, -1, -1),
        new SkillNode(SkillNodeType.STAT, [602], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 483, -1, -1),
        new SkillNode(SkillNodeType.STAT, [586], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 129, -1, -1),
        new SkillNode(SkillNodeType.STAT, [596, 576], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 272, -1, -1),
        new SkillNode(SkillNodeType.STAT, [595, 613, 577], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 121, -1, -1),
        new SkillNode(SkillNodeType.STAT, [579, 614, 598], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 433, -1, -1),
        new SkillNode(SkillNodeType.STAT, [580, 597, 615], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 493, -1, -1),
        new SkillNode(SkillNodeType.STAT, [581, 616, 592], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 604, -1, -1),
        new SkillNode(SkillNodeType.STAT, [582, 617, 611], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 532, -1, -1),
        new SkillNode(SkillNodeType.STAT, [618, 584, 612], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 188, -1, -1),
        new SkillNode(SkillNodeType.STAT, [585, 619, 593], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 365, -1, -1),
        new SkillNode(SkillNodeType.STAT, [604, 620, 586], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 343, -1, -1),
        new SkillNode(SkillNodeType.STAT, [621, 587, 603], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 454, -1, -1),
        new SkillNode(SkillNodeType.STAT, [606, 622, 589], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 231, -1, -1),
        new SkillNode(SkillNodeType.STAT, [590, 605], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 598, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [613], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 623, 45, -1),
        new SkillNode(SkillNodeType.STAT, [614], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 187, -1, -1),
        new SkillNode(SkillNodeType.STAT, [621], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 266, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [622], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 658, 46, -1),
        new SkillNode(SkillNodeType.STAT, [600], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 49, -1, -1),
        new SkillNode(SkillNodeType.STAT, [601], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 3, -1, -1),
        new SkillNode(SkillNodeType.STAT, [596, 607, 627], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 2, -1, -1),
        new SkillNode(SkillNodeType.STAT, [629, 608, 597], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 320, -1, -1),
        new SkillNode(SkillNodeType.STAT, [630, 625, 598], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 33, -1, -1),
        new SkillNode(SkillNodeType.STAT, [631, 617, 599], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 230, -1, -1),
        new SkillNode(SkillNodeType.STAT, [616, 632, 600], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 175, -1, -1),
        new SkillNode(SkillNodeType.STAT, [619, 601, 634], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 279, -1, -1),
        new SkillNode(SkillNodeType.STAT, [602, 618, 635], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 300, -1, -1),
        new SkillNode(SkillNodeType.STAT, [636, 626, 603], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 80, -1, -1),
        new SkillNode(SkillNodeType.STAT, [637, 604, 609], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 35, -1, -1),
        new SkillNode(SkillNodeType.STAT, [605, 610, 639], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 295, -1, -1),
        new SkillNode(SkillNodeType.CHEST, [630], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 629, 47, -1),
        new SkillNode(SkillNodeType.CHEST, [636], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 634, 48, -1),
        new SkillNode(SkillNodeType.STAT, [615], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 341, -1, -1),
        new SkillNode(SkillNodeType.STAT, [620], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 114, -1, -1),
        new SkillNode(SkillNodeType.PERK, [613, 628], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 171, -1, 35),
        new SkillNode(SkillNodeType.STAT, [629, 627], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 155, -1, -1),
        new SkillNode(SkillNodeType.STAT, [642, 628, 614], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 547, -1, -1),
        new SkillNode(SkillNodeType.STAT, [615, 623, 644], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 460, -1, -1),
        new SkillNode(SkillNodeType.STAT, [616, 645], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 46, -1, -1),
        new SkillNode(SkillNodeType.STAT, [646, 617, 640], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 115, -1, -1),
        new SkillNode(SkillNodeType.STAT, [647], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 276, -1, -1),
        new SkillNode(SkillNodeType.STAT, [648, 618, 641], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 583, -1, -1),
        new SkillNode(SkillNodeType.STAT, [619, 649], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 616, -1, -1),
        new SkillNode(SkillNodeType.STAT, [620, 624, 650], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 570, -1, -1),
        new SkillNode(SkillNodeType.STAT, [652, 621, 638], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 150, -1, -1),
        new SkillNode(SkillNodeType.STAT, [637, 639], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 445, -1, -1),
        new SkillNode(SkillNodeType.PERK, [638, 622], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 384, -1, 36),
        new SkillNode(SkillNodeType.CHEST, [632], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 648, 49, -1),
        new SkillNode(SkillNodeType.CHEST, [634], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 665, 50, -1),
        new SkillNode(SkillNodeType.STAT, [629, 653], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 87, -1, -1),
        new SkillNode(SkillNodeType.STAT, [654], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 612, -1, -1),
        new SkillNode(SkillNodeType.STAT, [655, 630, 645], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 1, -1, -1),
        new SkillNode(SkillNodeType.PERK, [631, 656, 644], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 552, -1, 37),
        new SkillNode(SkillNodeType.STAT, [658, 647, 632], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 94, -1, -1),
        new SkillNode(SkillNodeType.STAT, [648, 646, 633], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 473, -1, -1),
        new SkillNode(SkillNodeType.STAT, [659, 647, 634], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 306, -1, -1),
        new SkillNode(SkillNodeType.PERK, [661, 635, 650], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 352, -1, 38),
        new SkillNode(SkillNodeType.STAT, [649, 636, 662], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 59, -1, -1),
        new SkillNode(SkillNodeType.STAT, [663], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 438, -1, -1),
        new SkillNode(SkillNodeType.STAT, [664, 637], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 304, -1, -1),
        new SkillNode(SkillNodeType.STAT, [654, 642, 665], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 323, -1, -1),
        new SkillNode(SkillNodeType.STAT, [655, 653, 643], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 474, -1, -1),
        new SkillNode(SkillNodeType.STAT, [654, 666, 644], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 383, -1, -1),
        new SkillNode(SkillNodeType.STAT, [657, 667, 645], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 591, -1, -1),
        new SkillNode(SkillNodeType.STAT, [658, 656], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 522, -1, -1),
        new SkillNode(SkillNodeType.STAT, [657, 646, 668], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 424, -1, -1),
        new SkillNode(SkillNodeType.STAT, [660, 648, 670], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 120, -1, -1),
        new SkillNode(SkillNodeType.STAT, [661, 659], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 450, -1, -1),
        new SkillNode(SkillNodeType.STAT, [660, 671, 649], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 416, -1, -1),
        new SkillNode(SkillNodeType.STAT, [672, 663, 650], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 275, -1, -1),
        new SkillNode(SkillNodeType.STAT, [662, 664, 651], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 429, -1, -1),
        new SkillNode(SkillNodeType.STAT, [663, 652, 673], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 400, -1, -1),
        new SkillNode(SkillNodeType.PERK, [653], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 158, -1, 39),
        new SkillNode(SkillNodeType.STAT, [655, 667], SkillNodeSpawnId.NONE, SkillNodeRegion.DWARVES, 426, -1, -1),
        new SkillNode(SkillNodeType.STAT, [656, 666], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 541, -1, -1),
        new SkillNode(SkillNodeType.STAT, [669, 658], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 613, -1, -1),
        new SkillNode(SkillNodeType.PERK, [670, 668], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 160, -1, 40),
        new SkillNode(SkillNodeType.STAT, [659, 669], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 497, -1, -1),
        new SkillNode(SkillNodeType.STAT, [661, 672], SkillNodeSpawnId.NONE, SkillNodeRegion.MAGE, 337, -1, -1),
        new SkillNode(SkillNodeType.STAT, [662, 671], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 475, -1, -1),
        new SkillNode(SkillNodeType.PERK, [664], SkillNodeSpawnId.NONE, SkillNodeRegion.FOX, 505, -1, 41)
    ];
}